services:
  frontend:
    build:
      context: C:\Users\pilar\PROYECTO\securehub_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:9000
    networks:
      - app-network
  
  backend:
    build:
      context: C:\Users\pilar\PROYECTO\securehub_back
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

