apiVersion: v1
kind: PersistentVolume
metadata:
  name: freeipa-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  hostPath:
    path: "/mnt/data/freeipa"
