apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freeipa
  namespace: securehub
spec:
  serviceName: freeipa-service
  replicas: 1
  selector:
    matchLabels:
      app: freeipa
  template:
    metadata:
      labels:
        app: freeipa
    spec:
      hostname: freeipa.andion.eu
      subdomain: freeipa-service
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - freeipa
            topologyKey: "kubernetes.io/hostname"
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - freeipa.andion.eu
            - freeipa-0.freeipa-service.securehub.svc.cluster.local
      initContainers:
        - name: init
          image: quay.io/freeipa/freeipa-server:fedora-41-4.12.2
          command:
            - sh
            - /tmp/startup.sh
          volumeMounts:
            - name: freeipa-data
              mountPath: /data
            - name: ipa-options
              mountPath: /tmp/startup.sh
              subPath: startup.sh
            - name: ipa-options
              mountPath: /tmp/ipa-server-options
              subPath: ipa-server-options
      containers:
        - name: freeipa
          image: quay.io/freeipa/freeipa-server:fedora-41-4.12.2
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Ejecutando script de corrección del hostname..."
              sh /usr/local/bin/fix-hostname.sh
              echo "Iniciando instalación de FreeIPA..."
              ipa-server-install --unattended \
                --realm=ANDION.EU \
                --domain=andion.eu \
                --ds-password=$(IPA_DIRECTORY_PASSWORD) \
                --admin-password=$(IPA_ADMIN_PASSWORD) \
                --hostname=freeipa.andion.eu \
                --no-host-dns \
                --setup-dns \
                --forwarder=8.8.8.8 \
                --allow-zone-overlap \
                --skip-mem-check
          env:
            - name: TZ
              value: "Europe/Madrid"
            - name: IPA_SERVER_HOSTNAME
              value: "freeipa.andion.eu"
            - name: IPA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freeipa-secret
                  key: admin-password
            - name: IPA_DIRECTORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freeipa-secret
                  key: directory-password
          securityContext:
            privileged: true  # Necesario para systemd y cgroups
            seccompProfile:
              type: Unconfined  # systemd necesita permisos completos
            capabilities:
              add:
                - SYS_ADMIN
                - SYS_TIME
          stdin: true
          tty: true
          volumeMounts:
            - name: fix-hostname-script
              mountPath: /usr/local/bin/fix-hostname.sh
              subPath: fix-hostname.sh
            - name: freeipa-data
              mountPath: /data
            - name: run
              mountPath: /run
            - name: run-systemd
              mountPath: /run/systemd
            - name: tmp
              mountPath: /tmp
            - name: cgroups
              mountPath: /sys/fs/cgroup
            - name: log-journal
              mountPath: /var/log/journal
      volumes:
        - name: fix-hostname-script
          configMap:
            name: ipa-fix-hostname
        - name: freeipa-data
          persistentVolumeClaim:
            claimName: freeipa-pvc
        - name: run
          emptyDir:
            medium: Memory
        - name: run-systemd
          emptyDir:
            medium: Memory
        - name: ipa-options
          configMap:
            name: ipa-install-options
        - name: tmp
          emptyDir:
            medium: Memory
        - name: cgroups
          hostPath:  # Usa hostPath para cgroups
            path: /sys/fs/cgroup
            type: Directory
        - name: log-journal
          emptyDir: {}

