apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeipa-pvc
  namespace: securehub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual

