apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeipa-volume
  namespace: securehub
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
