apiVersion: v1
kind: Service
metadata:
  name: freeipa-service
  namespace: securehub
  annotations:
    metallb.universe.tf/address-pool: "primary"
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  selector:
    app: freeipa
  ports:
    - name: http
      port: 8081
      targetPort: 80
    - name: https
      port: 4433
      targetPort: 443
    - name: ldap
      port: 3899
      targetPort: 389
    - name: ldaps
      port: 3636
      targetPort: 636
    - name: kerberos
      port: 3388
      targetPort: 88
    - name: kpasswd
      port: 3464
      targetPort: 464
  type: LoadBalancer

