apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5-config
  namespace: securehub
data:
  krb5.conf: |
    [libdefaults]
        default_realm = ANDION.EU
        dns_lookup_realm = false
        dns_lookup_kdc = true
        ticket_lifetime = 24h
        forwardable = true

    [realms]
        ANDION.EU = {
            kdc = freeipa.andion.eu:433
            admin_server = freeipa.andion.eu:433
        }

    [domain_realm]
        .andion.eu = ANDION.EU
        andion.eu = ANDION.EU
