apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5-config
  namespace: securehub
data:
  krb5.conf: |
    [libdefaults]
        default_realm = ANDION.EU
        dns_lookup_realm = false
        dns_lookup_kdc = true
        ticket_lifetime = 24h
        forwardable = true

    [realms]
        SCRAP.STRAST.ES = {
            kdc = freeipa.andion.eu
            admin_server = freeipa.andion.eu
        }

    [domain_realm]
        .scrap.strast.es = ANDION.EU
        scrap.strast.es = ANDION.EU
