apiVersion: apps/v1
kind: Deployment
metadata:
  name: securehubback-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.servicePort }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets | first }}
