apiVersion: apps/v1
kind: Deployment
metadata:
  name: securehubfront-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.servicePort }}
          env:
            - name: REACT_APP_BACKEND_URL
              value: "{{ .Values.frontend.backendUrl }}"
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets | first }}
