apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freeipa-ingress
  namespace: securehub
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Fuerza la redirección de HTTP a HTTPS
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  # Comunicación al backend por HTTPS
spec:
  ingressClassName: nginx
  rules:
    - host: freeipa.com31-38.dit.upm.es  # Dominio usado para acceder desde fuera
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: freeipa-svc
                port:
                  number: 443  # Conexión al puerto HTTPS de FreeIPA
  tls:
    - hosts:
        - freeipa.com31-38.dit.upm.es
      secretName: freeipa-tls-secret  # Nombre del certificado TLS almacenado en Kubernetes