apiVersion: v1
kind: ConfigMap
metadata:
  name: freeipa-install-options
  namespace: securehub
data:
  startup.sh: |
    #!/bin/sh
    set -e  # Detener el script si hay algún error

    echo " Ejecutando startup.sh para FreeIPA..."
    echo "Copiando opciones de instalación..."
    cp /tmp/ipa-server-options /data/ipa-server-install-options

  ipa-server-options: |-
    --realm=ANDION.EU
    --domain=andion.eu
    --admin-password=${IPA_ADMIN_PASSWORD}
    --ds-password=${IPA_DIRECTORY_PASSWORD}
    --skip-mem-check
    --unattended
    --no-ntp
