apiVersion: v1
kind: PersistentVolume
metadata:
  name: freeipa-data-pv
  namespace: securehub
  labels:
    app: freeipa
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/freeipa-data2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeipa-data
  namespace: securehub
  labels:
    app: freeipa
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
