apiVersion: v1
kind: ConfigMap
metadata:
  name: freeipa-install-options
  namespace: securehub
data:
  startup.sh: |
    #!/bin/sh
    set -e  # Detener el script si hay algún error

    echo " Ejecutando startup.sh para FreeIPA..."
    echo "Copiando opciones de instalación..."
    cp /tmp/ipa-server-options /data/ipa-server-install-options

  ipa-server-options: |-
    --realm=ANDION.EU
    --domain=andion.eu
    --admin-password=Admin123!
    --ds-password=Direc123!
    --skip-mem-check
    --unattended
    --no-ntp
    --setup-dns
    --forwarder=1.1.1.1
    --no-dnssec-validation
    --forward-policy=only
    --allow-zone-overlap
